#MINIMAL KDE INSTALL
PACKAGES=(
'@base-x'
'bluedevil'
'breeze-gtk'
'plasma-discover'
'plasma-drkonqi'
'kde-gtk-config'
'kdeplasma-addons'
'kgamma'
'khotkeys'
'kinfocenter'
'kscreen'
'ksshaskpass'
'pam-kwallet'
'kwayland-integration'
'kwrited'
'plasma-browser-integration'
'plasma-desktop'
'plasma-disks'
'plasma-firewall'
'plasma-nm'
'plasma-pa'
'plasma-systemmonitor'
'plasma-thunderbolt'
'plasma-vault'
'plasma-workspace-wallpapers'
'powerdevil'
'sddm'
'sddm-kcm'
'sddm-breeze'
'xdg-desktop-portal-kde'
'konsole'
'kwrite'
'dolphin'
'ark'
'plasma-workspace-wayland'
'egl-wayland'
\@'Hardware Support'
'@Multimedia'
'@Fonts'
)
LANG=C sudo dnf install "${PACKAGES[@]}"


