[[panel]]
	position = "bottom"
	height = 16

	[[panel.applet]]
		name = "app-finder"

		icon_height = -1
		flat = true

		popover_width = -1
		popover_height = -1

		settings = "wcm"
		file_manager = "nautilus $HOME"

		[panel.applet.logout]
			shutdown = "systemctl poweroff"
			restart = "systemctl reboot"
			logout = "loginctl kill-user $USER"
			suspend = "systemctl suspend"
			hibernate = "systemctl hibernate"
			lock = "swaylock"

	[[panel.applet]]
		name = "task-switcher"
		[panel.applet.mode.scroll]
			[panel.applet.mode.scroll.button]
				gap = 8

	[[panel.applet]]
		name = "system-tray"

	[[panel.applet]]
		name = "volume-control"
		flat = true
		icon_height = 16

	[[panel.applet]]
		name = "clock"
